'use client';
import { useEffect, useRef, useState, type PointerEvent } from 'react';
import { Pencil, Eraser, Undo2, Redo2, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SIZE, coloredCount, type Pixels } from '@/lib/world';
export default function PixelEditor({pixels,onChange,label}:{pixels:Pixels;onChange:(p:Pixels)=>void;label:string}) {
 const canvas=useRef<HTMLCanvasElement>(null);const current=useRef(pixels);const drawing=useRef(false);const last=useRef<[number,number]|null>(null);const history=useRef<Pixels[]>([]);const redo=useRef<Pixels[]>([]);
 const [color,setColor]=useState('#667b56');const [erase,setErase]=useState(false);const [grid,setGrid]=useState(true);const [tick,setTick]=useState(0);const [hue,setHue]=useState(95);const [light,setLight]=useState(42);const [cursor,setCursor]=useState<[number,number]>([25,25]);
 useEffect(()=>{current.current=pixels;const ctx=canvas.current?.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,500,500);pixels.forEach((c,i)=>{if(c){ctx.fillStyle=c;ctx.fillRect((i%50)*10,Math.floor(i/50)*10,10,10);}});if(grid){ctx.strokeStyle='#626e5618';ctx.lineWidth=1;for(let i=0;i<=50;i++){ctx.beginPath();ctx.moveTo(i*10,0);ctx.lineTo(i*10,500);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*10);ctx.lineTo(500,i*10);ctx.stroke();}}},[pixels,grid]);
 const commitHistory=()=>{history.current=[...history.current.slice(-39),[...current.current]];redo.current=[];setTick(tick+1);};
 const point=(e:PointerEvent<HTMLCanvasElement>):[number,number]=>{const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(49,Math.floor((e.clientX-r.left)/r.width*50))),Math.max(0,Math.min(49,Math.floor((e.clientY-r.top)/r.height*50)))];};
 const paint=(pos:[number,number])=>{const next=[...current.current];const start=last.current??pos;const dx=pos[0]-start[0],dy=pos[1]-start[1],steps=Math.max(Math.abs(dx),Math.abs(dy));for(let i=0;i<=steps;i++){const t=steps?i/steps:0;next[Math.round(start[1]+dy*t)*50+Math.round(start[0]+dx*t)]=erase?null:color;}last.current=pos;current.current=next;onChange(next);setCursor(pos);};
 const undo=()=>{const prev=history.current.pop();if(prev){redo.current.push([...current.current]);onChange(prev);setTick(tick+1);}};
 const hsl=(h:number,l:number)=>{const a=.65*Math.min(l/100,1-l/100);const channel=(n:number)=>{const k=(n+h/30)%12;return Math.round(255*(l/100-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0');};return `#${channel(0)}${channel(8)}${channel(4)}`;};
 return <div className="pixel-editor"><div className="canvas-heading"><span>{label}</span><span>50 × 50 <span className="muted">/ {coloredCount(pixels)} 有色像素</span></span></div><canvas ref={canvas} width={500} height={500} tabIndex={0} role="img" aria-label={`${label}绘画画布，方向键移动，空格绘制。当前 ${cursor[0]+1}, ${cursor[1]+1}`} className="drawing-canvas" onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;last.current=null;commitHistory();paint(point(e));}} onPointerMove={e=>{if(drawing.current)paint(point(e));}} onPointerUp={()=>{drawing.current=false;last.current=null;}} onPointerCancel={()=>{drawing.current=false;last.current=null;}} onKeyDown={e=>{let [x,y]=cursor;if(e.key==='ArrowLeft')x--;else if(e.key==='ArrowRight')x++;else if(e.key==='ArrowUp')y--;else if(e.key==='ArrowDown')y++;else if(e.key===' '){e.preventDefault();commitHistory();last.current=null;paint(cursor);last.current=null;return;}else return;e.preventDefault();setCursor([Math.max(0,Math.min(49,x)),Math.max(0,Math.min(49,y))]);}}/>
 <div className="editor-toolbar"><Button className={`tool ${!erase?'active':''}`} aria-label="铅笔" aria-pressed={!erase} onClick={()=>setErase(false)}><Pencil/></Button><Button className={`tool ${erase?'active':''}`} aria-label="橡皮" aria-pressed={erase} onClick={()=>setErase(true)}><Eraser/></Button><div className="divider"/><Button className="tool" aria-label="撤销" disabled={!history.current.length} onClick={undo}><Undo2/></Button><Button className="tool" aria-label="重做" disabled={!redo.current.length} onClick={()=>{const next=redo.current.pop();if(next){history.current.push([...current.current]);onChange(next);setTick(tick+1);}}}><Redo2/></Button><Button className="tool" aria-label="清空画布，可撤销" onClick={()=>{commitHistory();onChange(Array(2500).fill(null));}}><Trash2/></Button><label className="grid-toggle"><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>网格</label></div>
 <div className="color-tools"><div className="color-wheel" role="slider" tabIndex={0} aria-label="色轮" aria-valuemin={0} aria-valuemax={359} aria-valuenow={Math.round(hue)} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();const h=(Math.atan2(e.clientY-r.top-r.height/2,e.clientX-r.left-r.width/2)*180/Math.PI+450)%360;setHue(h);setColor(hsl(h,light));setErase(false);}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const h=(hue+(e.key==='ArrowRight'?5:-5)+360)%360;setHue(h);setColor(hsl(h,light));}}><span style={{background:color}}/></div><div className="palette"><div className="swatches">{['#41473d','#667b56','#a7b590','#ceba94','#bd8069','#819aa6','#e6d0b3','#f9f5e9'].map(c=><button key={c} style={{background:c}} aria-label={`选择颜色 ${c}`} className={color===c?'chosen':''} onClick={()=>{setColor(c);setErase(false);}}/>)}</div><label className="lightness">明度<input type="range" min={5} max={95} value={light} onChange={e=>{const l=+e.target.value;setLight(l);setColor(hsl(hue,l));}}/></label><label className="custom-color"><input type="color" value={color} onChange={e=>{setColor(e.target.value);setErase(false);}}/>{color}</label></div></div></div>
}
